version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2:/127.0.0.1/root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
      ADMIN_EMAIL: 'admin@admin.com'
      ADMIN_PASSWORD: '123456abc'
    ports:
      - '8888:8888'
    volumes:
      - .:/katsuya-place
    links:
      - mysql
  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
