version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "Dockerfile" }}
          paths: ~/image.tar
      - run:
          command: |
            if [ ! -f ~/image.tar ]; then
              docker-compose build
              docker save $(docker images -q) -o ~/image.tar
            fi
      - save_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "Dockerfile" }}
          paths: ~/image.tar

  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "Dockerfile" }}
          paths: ~/image.tar

      - run: docker load -i ~/image.tar
      - run: docker-compose up -d

      - run: 
          name: sleep for image start
          command: sleep 10

      # DB setup
      - run: docker-compose run app rails db:create
      - run: docker-compose run app rails db:migrate
      - run: docker-compose run app rails db:seed

      - run: 
          name: create admin user
          command: docker-compose run app rails admin_user_management:add_user

      - run:
          name: run tests
          command: docker-compose run app rspec

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
