version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: docker-compose build

      - run: docker-compose up -d
      - run: sleep 10
      - run: docker-compose run app rails db:create
      - run: docker-compose run app rails db:migrate
      - run: docker-compose run app rails admin_user_management:add_user

      - run:
          name: run tests
          command: rspec
