version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d

      - run: 
          name: sleep for image start
          command: sleep 10

      # DB setup
      - run: docker-compose run app rails db:create
      - run: docker-compose run app rails db:migrate
      - run: docker-compose run app rails db:seed

      - run: 
          name: create admin user
          command: docker-compose run app rails admin_user_management:add_user

      - run:
          name: run tests
          command: docker-compose run app rspec
