version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: docker-compose build

      - run:
          name: sleep for db lunch
          command: sleep 10

      - run: docker-compose up -d
      - run: docker-compose run --rm app rails db:create
      - run: docker-compose run --rm app rails db:migrate
      - run: docker-compose run --rm app rails admin_user_management:add_user

      - run:
          name: run tests
          command: rspec
