version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: docker-compose build

      - run: docker-cmpose run --rm rails db:create
      - run: docker-cmpose run --rm rails db:migrate
      - run: docker-cmpose run --rm rails admin_user_management:add_user

      - run:
          name: run tests
          command: rspec
